collection/urls.py
from django.urls import path
from .views import *

app_name = 'collection'

urlpatterns = [
    path('', collections_list, name='list'),
    path('<int:id>/', collection_detail, name='detail'),
    path('create/', collection_create_update, name='create'),
    path('<int:collection_id>/update/', collection_create_update, name='update'),
    path('<int:collection_id>/delete/', collection_delete, name='delete'),
    path('nft/create/', nft_create, name='nft_create'),
    path('<int:collection_id>/nft/<int:nft_id>/', nft_detail, name='collection_nft_detail'),
    path('nft/<int:nft_id>/', nft_detail, name='nft_detail'),
    path('nft/<int:nft_id>/auction/<int:auction_id>/', nft_detail, name='auction_detail'),
    path('nft/<int:nft_id>/like/', nft_like, name='nft_like'),
    path('nft/<int:nft_id>/sell/', auction_create, name='auction_create'),
    path('auction/<int:auction_id>/sell/', auction_sell, name='auction_sell'),
    path('auction/<int:auction_id>/update', auction_update, name='auction_update'),
    path('auction/<int:auction_id>/delete', auction_delete, name='auction_delete'),
    path('auction/<int:auction_id>/bid/', auction_bid, name='auction_bid'),
    path('auction/<int:auction_id>/purchase/', auction_purchase, name='auction_purchase'),
    path('<str:username>/', collections_list, name='user_collections'),
    path('<str:username>/nfts/', collection_detail, name='user_nfts'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home.views import home_view
from users.views import login_register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_register_view, name='login'),
    path('', include('home.urls'), name='home'),
    path('collection/', include('collection.urls'), name='collection'),
    path('user/', include('users.urls'), name='user'),
    path('wallet/', include('wallet.urls'), name='wallet'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/collection-cards.html
{% for collection in page_obj %}
    <div class="collection-card">
        <div class="collection-card-desc">
            <div class="collection-card-title">
                <a href="{% url 'collection:detail' collection.id %}" class="collection-card-name">
                    {{ collection.name }}
                </a>
                <p class="collection-card-creator">@{{ collection.creator.username }}</p>
            </div>
            <div class="collection-card-detail">
                <div class="collection-creator-stats">
                    <div class="collection-creator-stat">
                        <p>Collections</p>
                        <h5>{{ collection.creator.collections.count }}</h5>
                    </div>
                    <div class="collection-creator-stat">
                        <p>Followers</p>
                        <h5 class="creator-followers-count">{{ collection.creator.followers.count }}</h5>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                {% if request.user == collection.creator %}
                    <a href="{% url 'collection:update' collection.id %}"><button class="btn-outline-green collection-card-btn">Update</button></a>
                {% elif collection.creator in following %}
                    <button class="btn-outline-green collection-card-btn follow-btn" data-user-id="{{ collection.creator.id }}">Following</button>
                {% else %}
                    <button class="btn-green collection-card-btn follow-btn" data-user-id="{{ collection.creator.id }}">Follow</button>
                {% endif %}
                {% endif %}
            </div>
        </div>
        {% if collection.nfts.exists %}
        <div class="collection-card-images">
            {% for nft in collection.nfts.all %}
                {% if forloop.counter <= 3 %}
                    <a href="{% url 'collection:detail' collection.id %}" class="collection-card-image">
                        <img src="{{ nft.image.url }}">
                    </a>
                {% endif %}
            {% endfor %}
            {% if collection.nfts.count > 3 %}
                <a href="{% url 'collection:detail' collection.id %}" class="collection-card-image">
                    <img src="{{ collection.nfts.all.3.image.url }}">
                    {% if collection.nfts.count > 4 %}
                        <p class="collection-more-image">+{{ collection.nfts.count|add:'-4' }}</p>
                    {% endif %}
                </a>
            {% endif %}
        </div> 
        {% else %}
            <div class="no-images">No nfts</div>
        {% endif %}
    </div>
{% empty %}
    <p>No collections found.</p>
{% endfor %}

templates/partials/nft-cards.html
{% for nft in page_obj %}
    <div class="nft-card">
        <a  {% if collection %}
                href="{% url 'collection:collection_nft_detail' collection.id nft.id %}"
            {% else %}
                href="{% url 'collection:nft_detail' nft.id %}"
            {% endif %}>
            <h4 class="nft-name">{{ nft.name }}</h4>
        </a>
        <a  {% if collection %}
                href="{% url 'collection:collection_nft_detail' collection.id nft.id %}"
            {% else %}
                href="{% url 'collection:nft_detail' nft.id %}"
            {% endif %}>
            <div class="nft-card-image">
                <img src="{{ nft.image.url }}" class="nft-image">
            </div>
        </a>
        <div class="nft-detail">
            {% if nft.get_status == 'auction' %}
                <div class="nft-status">
                    <p>Highest bid</p>
                    <h4 class="nft-price">{{ nft.auctions.first.price }} {{ nft.auctions.first.currency.symbol }}</h4>
                </div>
                <div class="nft-time">
                    <span class="countdown" data-date="{{ nft.auctions.first.end_time|date:'c' }}"></span>
                </div>
            {% elif nft.get_status == 'expired' %}
                <div class="nft-status">
                    <p>Highest bid</p>
                    <h4 class="nft-price">{{ nft.auctions.first.price }} {{ nft.auctions.first.currency.symbol }}</h4>
                </div>
                <div class="nft-time">
                    <span class="expired">Expired</span>
                </div>
            {% elif nft.get_status == 'not-started' %}
                <div class="nft-status nft-status-not-sale">
                    <h4>Not Started</h4>
                    <p>Starts at: {{ nft.auctions.first.start_time|date:"M d, Y" }}</p>
                </div>
            {% else %}
                <div class="nft-status nft-status-not-sale">
                    <h4>Not on sale</h4>
                </div>
            {% endif %}
        </div>
    </div>
{% empty %}
    <p>No NFTs found.</p>
{% endfor %}

templates/partials/subscriber-email.html
<html>
<body>
    <div class="container">
        <h1>Welcome to the NFTs Art Newsletter</h1>
        <p>Dear {{ name }}</p>
        <p>
            Thank you for signing up for our NFTs Art newsletter! We're thrilled to have you as part of our community.
        </p>
        <p>
            By subscribing, you'll be the first to know about:
        </p>
        <ul>
            <li>The latest updates in the world of digital art and NFTs.</li>
            <li>Exclusive previews of new product releases.</li>
            <li>Special offers and events that you won't want to miss.</li>
        </ul>
        <p>
            Stay tuned for your first edition of the NFTs Art newsletter, coming soon!
        </p>
        <p>
            Best regards,<br>
            The NFTs Art Team
        </p>
    </div>
</body>
</html>