collection/urls.py
from django.urls import path
from .views import *

app_name = 'collection'

urlpatterns = [
    path('', collections_list, name='list'),
    path('<int:id>/', collection_detail, name='detail'),
    path('create/', collection_create_update, name='create'),
    path('<int:collection_id>/update/', collection_create_update, name='update'),
    path('<int:collection_id>/delete/', collection_delete, name='delete'),
    path('nft/create/', nft_create, name='nft_create'),
    path('<int:collection_id>/nft/<int:nft_id>/', nft_detail, name='collection_nft_detail'),
    path('nft/<int:nft_id>/', nft_detail, name='nft_detail'),
    path('nft/<int:nft_id>/auction/<int:auction_id>/', nft_detail, name='auction_detail'),
    path('nft/<int:nft_id>/like/', nft_like, name='nft_like'),
    path('nft/<int:nft_id>/sell/', auction_create, name='auction_create'),
    path('auction/<int:auction_id>/sell/', auction_sell, name='auction_sell'),
    path('auction/<int:auction_id>/update', auction_update, name='auction_update'),
    path('auction/<int:auction_id>/delete', auction_delete, name='auction_delete'),
    path('auction/<int:auction_id>/bid/', auction_bid, name='auction_bid'),
    path('auction/<int:auction_id>/purchase/', auction_purchase, name='auction_purchase'),
    path('<str:username>/', collections_list, name='user_collections'),
    path('<str:username>/nfts/', collection_detail, name='user_nfts'),
]

core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home.views import home_view
from users.views import login_register_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_register_view, name='login'),
    path('', include('home.urls'), name='home'),
    path('collection/', include('collection.urls'), name='collection'),
    path('user/', include('users.urls'), name='user'),
    path('wallet/', include('wallet.urls'), name='wallet'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='index'),
    path('roadmap/', roadmap_view, name='roadmap'),
    path('ourclans/', ourclans_view, name='ourclans'),
    path('faq/', faq_view, name='faq'),
    path('get-in-touch/', get_in_touch, name='get-in-touch'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_register_view, name='login'),
    path('<int:user_id>/follow/', follow_user, name='follow'),
    path('forgot-password/', forgot_password, name='forgot_password'),
    path('verify-code/', verify_code, name='verify_code'),
    path('reset-password/', reset_password, name='reset_password'),
    path('logout/', logout_view, name='logout'),
    path('update/', update_profile, name='update_profile'),
    path('update-password/', update_password, name='update_password'),
]

wallet/urls.py
from django.urls import path
from .views import connect_wallet

app_name = 'wallet'

urlpatterns = [
    path('', connect_wallet, name='connect'),
]

collection/forms.py
from django import forms
from .models import NFT, Auction, Collection, Bid


class CollectionForm(forms.ModelForm):
    nfts = forms.ModelMultipleChoiceField(
        queryset=NFT.objects.none(), 
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    
    class Meta:
        model = Collection
        fields = ['blockchain', 'name', 'category', 'nfts']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['nfts'].queryset = NFT.objects.filter(collectors=user)
    

class NFTForm(forms.ModelForm):
    collections = forms.ModelMultipleChoiceField(
        queryset=Collection.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = NFT
        fields = ['name', 'description', 'image', 'blockchain', 'collections']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields['collections'].queryset = Collection.objects.filter(creator=user)


class AuctionForm(forms.ModelForm):
    class Meta:
        model = Auction
        fields = ['price', 'currency', 'start_time', 'end_time']


class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['amount', 'expiration']

collection/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import *
from .models import *
from users.models import User, Follow
from wallet.models import Wallet, Blockchain
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib import messages
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.db.models import Sum


def collections_list(request, username=None):
    if username:
        user = get_object_or_404(User, username=username)
        collections = Collection.objects.filter(creator=user)
        title = 'My Collections' if user == request.user else f"{user.fullname}'s Collections"
    else:
        collections = Collection.objects.all()
        title = 'Get Popular Collection'

    top_collectors = User.objects.annotate(
        total_auction_price=Sum('nfts__auctions__price')
    ).order_by('-total_auction_price')[:12]
    half_count = len(top_collectors) // 2
    if half_count > 4:
        top_collectors_1 = top_collectors[:half_count]
        top_collectors_2 = top_collectors[half_count:]
    else:
        top_collectors_1 = top_collectors
        top_collectors_2 = []
    
    categories = Category.objects.all()
    blockchains = Blockchain.objects.all()
    following = User.objects.filter(followers__follower=request.user) if request.user.is_authenticated else User.objects.none()

    search_query = request.GET.get('search', '')
    blockchain_filter = request.GET.get('blockchain', 'all')
    category_filter = request.GET.getlist('category')
    sort_by = request.GET.get('sort_by', 'default')

    if search_query:
        collections = collections.filter(name__icontains=search_query)

    if blockchain_filter != 'all' and blockchain_filter.isdigit():
        collections = collections.filter(blockchain__id=blockchain_filter)

    if category_filter:
        collections = collections.filter(category__id__in=category_filter)

    if sort_by == 'name-asc':
        collections = collections.order_by('name')
    elif sort_by == 'name-desc':
        collections = collections.order_by('-name')


    paginator = Paginator(collections, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        context = {
            'page_obj': page_obj,
            'following': following,
            'request': request
        }
        html = render_to_string('partials/collection-cards.html', context)
        return JsonResponse({'html': html})
   
    context = {
        'categories': categories,
        'blockchains': blockchains,
        'following': following,
        'title': title,
        'page_obj': page_obj,
        'paginator': paginator,
        'search_query': search_query,
        'blockchain_filter': blockchain_filter,
        'category_filter': category_filter,
        'sort_by': sort_by,
        'top_collectors_1': top_collectors_1,
        'top_collectors_2': top_collectors_2,
    }

    return render(request, 'collections.html', context)


def collection_detail(request, id=None, username=None): 
    if id:
        collection = get_object_or_404(Collection, id=id)
        collector = collection.creator
        nfts = collection.nfts.prefetch_related('auctions').all()
    elif username:
        collector = get_object_or_404(User, username=username)
        nfts = NFT.objects.filter(collectors=collector)
        collection = None

    top_collectors = User.objects.annotate(
        total_auction_price=Sum('nfts__auctions__price')
    ).order_by('-total_auction_price')[:12]
    half_count = len(top_collectors) // 2
    if half_count > 4:
        top_collectors_1 = top_collectors[:half_count]
        top_collectors_2 = top_collectors[half_count:]
    else:
        top_collectors_1 = top_collectors
        top_collectors_2 = []
    
    currencies = Currency.objects.all()
    following = Follow.objects.filter(follower=request.user, following=collector).exists() if request.user.is_authenticated else False
    
    status_filters = request.GET.getlist('status')
    min_value = request.GET.get('min')
    max_value = request.GET.get('max')
    currency_filter = request.GET.get('currency', 'all')
    search_query = request.GET.get('search', '')
    sort_by = request.GET.get('sort_by', 'default')

    if min_value or max_value or currency_filter != 'all':
        nfts = nfts.filter(auctions__isnull=False)
        if min_value:
            nfts = nfts.filter(auctions__price__gte=min_value)
        if max_value:
            nfts = nfts.filter(auctions__price__lte=max_value)
        if currency_filter != 'all':
            nfts = nfts.filter(auctions__currency__symbol=currency_filter)

    if search_query:
        nfts = nfts.filter(name__icontains=search_query)
    
    if sort_by == 'price-asc':
        nfts = nfts.filter(auctions__isnull=False).order_by('auctions__price')
    elif sort_by == 'price-desc':
        nfts = nfts.filter(auctions__isnull=False).order_by('-auctions__price')
    elif sort_by == 'name-asc':
        nfts = nfts.order_by('name')
    elif sort_by == 'name-desc':
        nfts = nfts.order_by('-name')

    if sort_by == 'price-asc' or sort_by == 'price-desc' or min_value or max_value:
        nfts = [nft for nft in nfts if nft.get_status() == 'auction']
    
    if status_filters:
        nfts = [nft for nft in nfts if nft.get_status() in status_filters]

    paginator = Paginator(nfts, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
        
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        context = {
            'page_obj': page_obj,
            'collection': collection,
        }
        html = render_to_string('partials/nft-cards.html', context)
        return JsonResponse({'html': html})
    
    context = {
        'collection': collection,
        'collector': collector,
        'currencies': currencies,
        'following': following,
        'page_obj': page_obj,
        'paginator': paginator,
        'status_filters': status_filters,
        'min_value': min_value,
        'max_value': max_value,
        'currency_filter': currency_filter,
        'search_query': search_query,
        'sort_by': sort_by,
        'top_collectors_1': top_collectors_1,
        'top_collectors_2': top_collectors_2,
        'username': username,
    }
    return render(request, 'collection-detail.html', context)


@login_required
def collection_create_update(request, collection_id=None):
    blockchains = Blockchain.objects.all()
    categories = Category.objects.all()
    collection = get_object_or_404(Collection, id=collection_id, creator=request.user) if collection_id else None
    nfts = NFT.objects.filter(collectors=request.user)
    
    if request.method == 'POST':
        form = CollectionForm(request.POST, instance=collection, user=request.user)
        if form.is_valid():
            collection = form.save(commit=False)
            collection.creator = request.user
            collection.save()
            form.save_m2m()

            if collection_id:
                messages.success(request, 'Collection updated successfully.')
            else:
                messages.success(request, 'Collection created successfully.')

            next_url = request.GET.get('next') or request.POST.get('next')
            if next_url:
                return redirect(next_url)
            
            return redirect('collection:user_collections', request.user.username)
    else:
        form = CollectionForm(instance=collection, user=request.user)

    context = {
        'form': form,
        'blockchains': blockchains,
        'categories': categories,
        'is_update': collection_id is not None,
        'collection': collection,
        'nfts': nfts,
    }

    return render(request, 'collection-create.html', context)


@login_required
def collection_delete(request, collection_id):
    collection = get_object_or_404(Collection, id=collection_id)
    collection.delete()
    messages.success(request, 'Collection deleted successfully.')
    return redirect('collection:user_collections', request.user.username)


def nft_detail(request, nft_id, collection_id=None, auction_id = None):
    nft = get_object_or_404(NFT, id=nft_id)
    collection = get_object_or_404(Collection, id=collection_id) if collection_id else nft.collections.first()
    collection_nfts = collection.nfts.exclude(id=nft.id)[:4] if collection else None
    auction = get_object_or_404(Auction, id=auction_id) if auction_id else nft.auctions.first()
    liked = Like.objects.filter(nft=nft, user=request.user).exists() if request.user.is_authenticated else False
    status = nft.get_status(auction)
    bids = Bid.objects.filter(auction=auction).order_by('timestamp') if auction else None
    bid_amounts = [float(bid.amount) for bid in bids] if bids else []
    bid_timestamps = [bid.timestamp.isoformat() for bid in bids] if bids else []
    
    context = {
        'nft': nft,
        'collection': collection,
        'collection_nfts': collection_nfts,
        'auction': auction,
        'status': status,
        'liked': liked,
        'bids': bids,
        'bid_amounts': bid_amounts,
        'bid_timestamps': bid_timestamps,
    }
    return render(request, 'nft-detail.html', context)


@login_required
def nft_create(request):
    collections = Collection.objects.filter(creator=request.user)
    blockchains = Blockchain.objects.all()
    if request.method == 'POST':
        form = NFTForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            nft = form.save(commit=False)
            nft.creator = request.user
            nft.save()
            nft.collectors.add(request.user)
            nft.collections.set(form.cleaned_data.get('collections'))

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            NFTs Art
        {% endblock title %}
    </title>
    <link rel="shortcut icon" href="{% static '/img/icons/gear.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/responsive.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
        <div class="container">
            <div class="navbar">
                <a href="{% url 'home' %}" class="nav-brand">
                    <h3>NFTs Art</h3>
                </a>
                <ul class="nav-links">
                    <li class="nav-item"><a href="{% url 'collection:list' %}" class="nav-link">Collection</a></li>
                    <li class="nav-item"><a href="{% url 'home:roadmap' %}" class="nav-link">Road Map</a></li>
                    <li class="nav-item"><a href="{% url 'home:ourclans' %}" class="nav-link">Our Clans</a></li>
                    <li class="nav-item"><a href="{% url 'home:faq' %}" class="nav-link">FAQ</a></li>
                </ul>
                <div class="nav-buttons">
                    {% if request.user.is_authenticated %}
                        <a class="nav-button" href="{% url 'collection:nft_create' %}"><button class="btn-green">Create</button></a>
                        <div class="avatar nav-button">
                            <a href="{% url 'user:update_profile' %}">
                                <img class="avatar-img" src="{{ user.avatar.image.url }}">
                            </a>
                            <div class="avatar-icons">
                                <div class="verified-icon">
                                    <i class="star-icon"></i>
                                    <i class="fa-solid fa-check check-icon"></i>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <a class="nav-button" href="{% url 'user:login' %}?next={{ request.path }}">
                            <button class="btn-green">Login</button>
                        </a>
                    {% endif %}

                    <i id="nav-menu-icon">
                        <hr>
                        <hr>
                    </i>
                </div>
            </div>
            <div class="nav-menu" id="nav-menu">
                <div class="nav-menu-buttons">
                    {% if request.user.is_authenticated %}
                        <div class="avatar">
                            <a href="{% url 'user:update_profile' %}">
                                <img class="avatar-img" src="{{ user.avatar.image.url }}">
                            </a>
                            <div class="avatar-icons">
                                <div class="verified-icon">
                                    <i class="star-icon"></i>
                                    <i class="fa-solid fa-check check-icon"></i>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'collection:nft_create' %}"><button class="btn-green">Create</button></a>
                    {% else %}
                        <a href="{% url 'user:login' %}?next={{ request.path }}">
                            <button class="btn-green">Login</button>
                        </a>
                    {% endif %}
                </div>
                <ul class="nav-menu-links">
                    <li class="nav-item"><a href="{% url 'collection:list' %}" class="nav-link">Collection</a></li>
                    <li class="nav-item"><a href="{% url 'home:roadmap' %}" class="nav-link">Road Map</a></li>
                    <li class="nav-item"><a href="{% url 'home:ourclans' %}" class="nav-link">Our Clans</a></li>
                    <li class="nav-item"><a href="{% url 'home:faq' %}" class="nav-link">FAQ</a></li>
                </ul>
            </div>
        </div>
    </header>

    <main>
        <section class="messages-section">
            <div class="container">
                <div class="messages" id="messages">
                {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
                {% endif %}
                </div>
            </div>
        </section>

        {% block main %}
        {% endblock main %}
    </main>

    <footer>
        <div class="container">
            <div class="footer">
                <div class="footer-logo-desc">
                    <h3 class="footer-logo">NFTs Art</h3>
                    <h4 class="footer-desc">Create sell, and collect <br> NFT digital art</h4>
                </div>
                <div class="footer-links">
                    <ul class="footer-menu">
                        <li><a href="{% url 'collection:list' %}" class="footer-link">Collection</a></li>
                        <li><a href="{% url 'home:roadmap' %}" class="footer-link">Road Map</a></li>
                        <li><a href="{% url 'home:ourclans' %}" class="footer-link">Our Clans</a></li>
                        <li><a href="{% url 'home:faq' %}" class="footer-link">FAQ</a></li>
                    </ul>
                    <ul class="footer-social">
                        <li><a href="#"><i class="fa-brands fa-discord"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                        <li>
                            <div id="theme-toggle">
                                <i class="fa-solid fa-moon"></i>
                            </div>
                        </li>
                    </ul>
                    <div class="footer-rights">
                        <p>2024. all right Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static '/js/main.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</body>

</html>

templates/nft-sell.html
{% extends "layout.html" %}

{% block title %}
    {% if operation == 'update' %}
        Update Auction
    {% else %}
        List for Sale
    {% endif %}
{% endblock title %}

{% block main %}

<section class="form-section">
    <div class="container">
        <div class="form-container">
            <h2 class="section-title">
                {% if operation == 'update' %}
                    Update Auction
                {% else %}
                    List Item for Sale
                {% endif %}
            </h2>
            <form class="form" id="nft-sell-form" method="post">
                {% csrf_token %}
                <div class="form-preview">
                    <h4 class="form-subtitle">Preview</h4>
                    <h3 class="nft-sell-name">{{ nft.name }}</h3>
                    <div class="nft-form-image">
                        <img src="{{ nft.image.url }}" alt="NFT Image">
                    </div>
                    <div class="nft-sell-price">
                        <p>Price</p>
                        <h4 id="price-display">0</h4>
                    </div>
                </div>
                <div class="form-inputs-container">
                    <div class="form-inputs">
                        <div class="form-control">
                            <label for="price" class="form-label">Price</label>
                            <div class="nft-sell-price-inputs">
                                <select id="currency" name="currency" class="form-select">
                                {% for currency in currencies %}
                                    <option class="form-option" value="{{ currency.id }}"
                                        {% if auction and auction.currency.id == currency.id %}selected{% endif %}>
                                        {{ currency.symbol }}
                                    </option>
                                {% endfor %}
                                </select>
                                {% if form.currency.errors %}
                                    <div class="form-warning">{{ form.currency.errors }}</div>
                                {% endif %}
                                <input type="number" id="price-input" name="price" class="form-input" placeholder="Type here..." step="0.01"
                                    {% if auction %}value="{{ auction.price }}"{% endif %}>
                                {% if form.price.errors %}
                                    <div class="form-warning">{{ form.price.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-control">
                            <label for="schedule-time" class="form-label">Schedule Listing</label>
                            <select id="schedule-time" name="schedule-time" class="form-select">
                                <option class="form-option" value="3-month">3 Month</option>
                                <option class="form-option" value="6-month" selected>6 Month</option>
                                <option class="form-option" value="1-year">1 Year</option>
                                <option class="form-option" value="2-year">2 Year</option>
                                <option class="form-option" value="5-year">5 Year</option>
                            </select>
                            {% if form.schedule_time.errors %}
                                <div class="form-warning">{{ form.schedule_time.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="form-control-dates">
                            <div class="form-control">
                                <label for="start-time" class="form-label">Starting</label>
                                <input type="date" name="start_time" id="start-time" class="form-input"
                                    {% if auction %}value="{{ auction.start_time|date:'Y-m-d' }}"{% endif %} required>
                                {% if form.start_time.errors %}
                                    <div class="form-warning">{{ form.start_time.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="form-control">
                                <label for="end-time" class="form-label">Ending</label>
                                <input type="date" name="end_time" id="end-time" class="form-input"
                                    {% if auction %}value="{{ auction.end_time|date:'Y-m-d' }}"{% endif %} required>
                                {% if form.end_time.errors %}
                                    <div class="form-warning">{{ form.end_time.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="form-checkboxes">
                        <div class="form-info">
                            <label class="form-label">
                                Service Fee
                                <i class="fa-solid fa-circle-info"></i>
                            </label>
                            <h5>2.5%</h5>
                        </div>
                        <div class="form-checkbox">
                            <div class="form-checkbox-label">
                                <label for="reserve-for-buyer" class="form-label">Reserve for specific buyer</label>
                            </div>
                            <input type="checkbox" id="reserve-for-buyer" class="form-checkbox-input hidden">
                            <label for="reserve-for-buyer" class="checkbox-icon"></label>
                        </div>
                    </div>
                    <div class="form-buttons">
                        <button type="submit" class="form-button btn-green" id="complete-listing-btn">
                            {% if operation == 'update' %}
                                Update Auction
                            {% else %}
                                Complete Listing
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

{% if operation == 'sell' %}
<section class="popup-section active" id="listing-popup" >
    <div class="popup">
        <div class="popup-header">
            <h3 class="popup-title">Complete Your Listing</h3>
            <p class="popup-desc">Sign a message using your wallet <br> to continue</p>
        </div>
        <div class="popup-card">
            <div class="popup-card-image">
                <img src="{{ nft.image.url }}" class="nft-image">
            </div>
            <div class="popup-card-desc">
                <h4 class="nft-name">{{ nft.name }}</h4>
                <div class="nft-detail">
                    <div class="nft-highest-bid">
                        <p>Highest bid</p>
                        <h4 id="popup-price">{{ auction.price}} {{ auction.currency.symbol }}</h4>
                    </div>
                    <div class="nft-time">
                        <span id="popup-end-time" class="countdown" data-date="{{ auction.end_time|date:'c' }}"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="popup-buttons">
            <a href="{% url 'wallet:connect' %}?next={{ request.path }}">
                <button class="btn-green" id="sign-btn">Sign</button>
            </a>
        </div>
    </div>
</section>
{% endif %}

{% if operation == 'sell' and wallet %}
<section class="popup-section active" id="completed-popup">
    <div class="popup">
        <div class="popup-header">
            <h3 class="popup-title">Your NFT is Listed!</h3>
            <p class="popup-desc">Awesome! You've listed <span>{{ nft.name }}</span></p>
        </div>
        <div class="popup-card">
            <div class="popup-card-image">
                <img src="{{ nft.image.url }}" class="nft-image">
            </div>
            <div class="popup-card-desc">
                <h4 class="nft-name">{{ nft.name }}</h4>
                <div class="nft-detail">
                    <div class="nft-highest-bid">
                        <p>Highest bid</p>
                        <h4 id="popup-price">{{ auction.price}} {{ auction.currency.symbol }}</h4>
                    </div>
                    <div class="nft-time">
                        <span id="popup-end-time" class="countdown" data-date="{{ auction.end_time|date:'c' }}"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="popup-share">
            <div class="popup-nft-link">
                <p class="popup-wallet-link" data-key="{{ wallet.key }}">{{ wallet.key }}</p>
                <i class="fa-regular fa-copy wallet-copy-btn"></i>
            </div>
            <div class="popup-share-via">
                <hr>
                <p>Or Share Via</p>
                <hr>
            </div>
            <div class="popup-share-icons">
                <i class="fa-brands fa-discord"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-facebook"></i>
            </div>
        </div>
        <a href="{% url 'collection:auction_detail' nft.id auction.id %}" class="popup-close-btn">
            <i class="fa-solid fa-xmark"></i>
        </a>
    </div>
</section>
{% endif %}

{% endblock main %}